In [1]:
import os
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import urllib.request
import csv

In [2]:
anti_accounts_path = r'C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2'
pro_accounts_path = r'C:\Users\psrub\Documents\Python\Twitter\pro_scientific_data_2'

In [3]:
anti_accounts = os.listdir(anti_accounts_path)
pro_accounts = os.listdir(pro_accounts_path)

In [4]:
tweets_dfs = []

for account in anti_accounts:
    acc_path = os.path.join(anti_accounts_path, account)
    try: 
        print(os.path.join(acc_path, 'tweets.json'))
        df = pd.read_json(os.path.join(acc_path, 'tweets.json'))
        df['account'] = account
        tweets_dfs.append(df)
    except ValueError:
        continue

anti_df = pd.concat(tweets_dfs, ignore_index=True)
anti_df['class'] = 1

tweets_dfs = []
        
for account in pro_accounts:
    acc_path = os.path.join(pro_accounts_path, account)
    try: 
        print(os.path.join(acc_path, 'tweets.json'))
        df = pd.read_json(os.path.join(acc_path, 'tweets.json'))
        df['account'] = account
        tweets_dfs.append(df)
    except ValueError:
        continue
        
pro_df = pd.concat(tweets_dfs, ignore_index=True)
pro_df['class'] = 0

df = pd.concat([anti_df, pro_df], ignore_index=True)

C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@5gAwareness\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@5GAwarenessNow\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@5gDangers\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@AlternMedicine1\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@AMGuide\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@Anastas32451695\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@AncestralApoth\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@AnnleeElisha\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@avoiceforchoice\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@BusyDrT\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@CAchemtrails\tweets.json
C:\Users\psrub\Documen

C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@riteaid\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@RobertKennedyJr\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@sayerjigmi\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@Scotland5g\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@Spacehehehe\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@Stop5G\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@STOP5G_STOP5G\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@SydneyChemtrail\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@TheFlatEartherr\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@TomSoenen1\tweets.json
C:\Users\psrub\Documents\Python\Twitter\anti_scientific_data_2\@truthvaxwarrior\tweets.json
C:\Users\psrub\Documents\P

In [5]:
english_stopwords = stopwords.words("english")

In [6]:
df['filtered_text'] = df['clean_text'].apply(lambda x: ' '.join([word for word in x.split() if word not in english_stopwords]))

In [7]:
df_grouped_text = df.groupby(['account', 'class'], as_index = False).agg({'filtered_text': ' '.join})

In [8]:
df_grouped_text

account  class  \
0        @2020science      0   
1     @5GAwarenessNow      1   
2        @5gAwareness      1   
3          @5gDangers      1   
4    @AlternMedicine1      1   
..                ...    ...   
156          @vaxxed2      1   
157  @wanderinganimal      1   
158            @wddty      1   
159         @yattypat      1   
160   TNaturalHealing      1   

                                         filtered_text  
0    Have reached peak produce labeling?! Congrats ...  
1    shes hot too. matter...but matters _FTW ZING! ...  
2    Oh like masonic father locked hilary? Oops!! I...  
3    What us look real climate science known long t...  
4    Colombian Insurance Providers Required To Cove...  
..                                                 ...  
156  Make sure go website sign email list join tele...  
157  _ 1 But read tweets talking unresearched Georg...  
158  Air pollution could big factor influences seve...  
159  _says _ukulele And suicides? Fatal car acciden...  
160  _sarig You guys better crush earnings Nov 8th ...  

[161 rows x 3 columns]

In [9]:
from transformers import AutoModelForSequenceClassification
from transformers import TFAutoModelForSequenceClassification
from transformers import AutoTokenizer

In [10]:
! nvidia-smi

Sun Jan 23 14:53:15 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 497.29       Driver Version: 497.29       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| 27%   57C    P0    33W / 120W |    522MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [11]:
import torch
from transformers import __version__ as transformers_version
from torch import __version__ as torch_version

In [12]:
device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu')

In [13]:
print(f'Using device: {device}')

Using device: cuda:0


In [14]:
task='sentiment'
MODEL = f"cardiffnlp/twitter-roberta-base-{task}"

In [15]:
tokenizer = AutoTokenizer.from_pretrained(MODEL)

In [16]:
labels = ['negative', 'neutral', 'positive']

In [17]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL).to(device)

In [18]:
model

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0): RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerN

In [19]:
from torch import sigmoid
from scipy.special import softmax

In [52]:
def predict(text, tokenizer, model):
    encoded = tokenizer(text, truncation=True, max_length=512, padding=True, return_tensors='pt').to(device)
    model_output = model(**encoded)
    
    return sigmoid(model_output.logits)[0].cpu().detach().numpy()

def predict_batch(texts, tokenizer, model):
    return [predict(text, tokenizer, model) for text in texts]

def predict_hf(text, tokenizer, model):

    encoded_input = tokenizer(text, truncation=True, padding=True, max_length=512, return_tensors='pt').to(device)
    output = model(**encoded_input)
    scores = output[0][0].cpu().detach().numpy()
    return softmax(scores)

def predict_batch_hf(texts, tokenizer, model):
    return [predict(text, tokenizer, model) for text in texts]

In [21]:
def print_results(result, labels):
    ranking = np.argsort(result)
    ranking = ranking[::-1]

    for i in range(result.shape[0]):
        l = labels[ranking[i]]
        s = result[ranking[i]]
        print(f"{i+1}) {l} {np.round(float(s), 4)}")

In [43]:
pro0 = df_grouped_text.iloc[0]['filtered_text']
anti0 = df_grouped_text.iloc[1]['filtered_text']

In [48]:
res = predict(anti0, tokenizer, model)
res

array([0.8913398 , 0.5082953 , 0.08866754], dtype=float32)

In [49]:
res_hf = predict_hf(anti0, tokenizer, model)
res_hf

array([0.8788267 , 0.11074962, 0.01042361], dtype=float32)

In [50]:
print_results(res, labels)

1) negative 0.8913
2) neutral 0.5083
3) positive 0.0887


In [51]:
print_results(res_hf, labels)

1) negative 0.8788
2) neutral 0.1107
3) positive 0.0104


In [93]:
df_grouped_text

account  class  \
0        @2020science      0   
1     @5GAwarenessNow      1   
2        @5gAwareness      1   
3          @5gDangers      1   
4    @AlternMedicine1      1   
5         @AmyMainzer      0   
6    @Anastas32451695      1   
7     @AncestralApoth      1   
8       @AnnleeElisha      1   
9       @Atul_Gawande      0   
10     @BadAstronomer      0   
11      @CAchemtrails      1   
12      @CHEMTRAILSMN      1   
13     @CaliVaxChoice      1   
14      @Canoe_Glider      1   
15    @ChemtrailsNews      1   
16     @Chemtrails_UK      1   
17           @DSL1912      1   
18       @DanTGilbert      0   
19     @DinosaurEarth      1   
20          @DrButtar      1   
21   @DrChrisNorthrup      1   
22             @DrVes      0   
23          @EMFRebel      1   
24       @EndTheGlobe      1   
25         @EricTopol      0   
26        @FlatArthur      1   
27     @FlatAwakening      1   
28     @FlatEarthBaba      1   
29     @FlatEarthCity      1   
30   @FlatEarthEffect      1   
31      @FlatEarthOrg      1   
32   @FlatEarthTshirt      1   
33         @FlatRealm      1   
34       @FlatSmacker      1   
35        @GMOFreeUSA      1   
36   @GlobalCHEMTRAIL      1   
37           @Gylauer      1   
38       @HansRosling      0   
39           @HegKong      1   
40      @HighWireTalk      1   
41          @JCVenter      0   
42     @JakeMaverick5      1   
43     @JasminMartino      1   
44   @JohnAllenPaulos      0   
45       @JustWakeUp8      1   
46      @KenzoAmariyo      1   
47       @KimShute_NY      1   
48        @Knowfree77      1   
49          @LKrauss1      0   
50         @LabSpaces      0   
51   @LaurenceBacchus      1   
52    @LookTheFuckUp_      1   
53       @Lumineuse72      1   
54    @MakimuraYusaku      1   
55    @MarcusduSautoy      0   
56     @MargoCatholic      1   
57       @MedicineAlt      1   
58      @MichaelEMann      0   
59   @MyLindseyMcKeon      1   
60      @NickHudsonCT      1   
61    @Novaccineforce      1   
62       @OliverSacks      0   
63      @OpChemtrails      1   
64   @OrganicConsumer      1   
65      @PdxTreehouse      1   
66      @ProfBrianCox      0   
67      @ProfRWinston      0   
68       @QMFlatEarth      1   
69   @RandomSpaceFact      0   
70     @RebeccaSkloot      0   
71    @RichardDawkins      0   
72    @RichardWiseman      0   
73   @RobertKennedyJr      1   
74     @STOP5G_STOP5G      1   
75      @SamHarrisOrg      0   
76    @SebastianThrun      0   
77       @SethShostak      0   
78       @Spacehehehe      1   
79            @Stop5G      1   
80   @SydneyChemtrail      1   
81   @TheFlatEartherr      1   
82             @US4MF      1   
83        @VAware1986      1   
84   @VaccineEdLeague      1   
85     @VaccineResist      1   
86    @VitalityOnline      1   
87          @Vomit911      1   
88   @WorldwideHealth      1   
89    @YouthAgainst5G      1   
90             @_CSHD      1   
91       @bengoldacre      0   
92           @bgreene      0   
93      @carolynporco      0   
94     @circleofmamas      1   
95         @danariely      0   
96        @danlevitin      0   
97       @deborahblum      0   
98        @delbigtree      1   
99       @dgmacarthur      0   
100          @dmarble      1   
101     @drsimonegold      1   
102   @earthisaplane7      1   
103        @edyong209      0   
104     @ehs_symptoms      1   
105     @facebones777      1   
106  @flat_earth_dude      1   
107         @flat_its      1   
108  @flatearthaddict      1   
109    @flatearthohio      1   
110    @forcedanarchy      1   
111   @forrestmaready      1   
112           @heru41      1   
113           @hhnews      1   
114       @hidenhand1      1   
115    @itsBentooLong      1   
116     @jrickerthall      1   
117    @keepit1002018      1   
118          @kejames      0   
119    @kellybroganmd      1   
120     @kevdjenkins1      1   
121         @kinggary      0   
122      @laurencette      1   
123   @lifebiomedguru      1   
124          @

In [55]:
texts = df_grouped_text['filtered_text'].tolist()

In [57]:
results = predict_batch(texts, tokenizer, model)

In [58]:
results_hf = predict_batch_hf(texts, tokenizer, model)

In [59]:
results

[array([0.10254617, 0.49881205, 0.9246107 ], dtype=float32),
 array([0.8913398 , 0.5082953 , 0.08866754], dtype=float32),
 array([0.5062443 , 0.6621156 , 0.30783287], dtype=float32),
 array([0.7357953 , 0.56522065, 0.18659955], dtype=float32),
 array([0.450417  , 0.77969396, 0.2321847 ], dtype=float32),
 array([0.13525856, 0.53546816, 0.8793984 ], dtype=float32),
 array([0.10639387, 0.47303596, 0.93581635], dtype=float32),
 array([0.11960267, 0.6556464 , 0.79717916], dtype=float32),
 array([0.21489464, 0.5167548 , 0.8185754 ], dtype=float32),
 array([0.4102565, 0.6323186, 0.4496942], dtype=float32),
 array([0.39473087, 0.57593393, 0.56348085], dtype=float32),
 array([0.6304379 , 0.7015158 , 0.16219273], dtype=float32),
 array([0.49759525, 0.7384987 , 0.24972612], dtype=float32),
 array([0.66515344, 0.655881  , 0.18943617], dtype=float32),
 array([0.45463136, 0.7655745 , 0.24894434], dtype=float32),
 array([0.5208452 , 0.6586246 , 0.31241286], dtype=float32),
 array([0.7235909 , 0.64863

In [69]:
results_df = pd.DataFrame([r.tolist() for r in results])

In [70]:
results_df['prediction'] = np.argmax(results_df[[0, 1, 2]].to_numpy(), axis=-1)

In [71]:
results_df['class'] = df_grouped_text['class'].tolist()

In [85]:
pd.set_option('display.max_rows', None)

In [87]:
# negative - 0
# neutral - 1 
# positive - 2

results_df

0         1         2  prediction  class
0    0.102546  0.498812  0.924611           2      0
1    0.891340  0.508295  0.088668           0      1
2    0.506244  0.662116  0.307833           1      1
3    0.735795  0.565221  0.186600           0      1
4    0.450417  0.779694  0.232185           1      1
5    0.135259  0.535468  0.879398           2      0
6    0.106394  0.473036  0.935816           2      1
7    0.119603  0.655646  0.797179           2      1
8    0.214895  0.516755  0.818575           2      1
9    0.410257  0.632319  0.449694           1      0
10   0.394731  0.575934  0.563481           1      0
11   0.630438  0.701516  0.162193           1      1
12   0.497595  0.738499  0.249726           1      1
13   0.665153  0.655881  0.189436           0      1
14   0.454631  0.765575  0.248944           1      1
15   0.520845  0.658625  0.312413           1      1
16   0.723591  0.648639  0.144848           0      1
17   0.386938  0.600018  0.534007           1      1
18   0.230063  0.536431  0.790575           2      0
19   0.528681  0.631339  0.328937           1      1
20   0.842871  0.533635  0.115462           0      1
21   0.062248  0.673162  0.898006           2      1
22   0.271917  0.651843  0.589307           1      0
23   0.696126  0.615073  0.190292           0      1
24   0.420527  0.726503  0.320084           1      1
25   0.420829  0.616327  0.451394           1      0
26   0.700875  0.592338  0.206982           0      1
27   0.369616  0.647212  0.492697           1      1
28   0.494137  0.818126  0.167224           1      1
29   0.731619  0.643961  0.138827           0      1
30   0.058196  0.852220  0.730293           1      1
31   0.618307  0.586321  0.297972           0      1
32   0.218838  0.761525  0.533851           1      1
33   0.114406  0.743255  0.723973           1      1
34   0.510592  0.535730  0.452863           1      1
35   0.710059  0.632455  0.158523           0      1
36   0.713489  0.683796  0.130950           0      1
37   0.362472  0.798186  0.296027           1      1
38   0.302612  0.645349  0.556045           1      0
39   0.490750  0.574472  0.431437           1      1
40   0.660620  0.708978  0.150856           1      1
41   0.617825  0.620355  0.262060           1      0
42   0.825405  0.583174  0.106443           0      1
43   0.152557  0.420727  0.931454           2      1
44   0.539422  0.608491  0.342120           1      0
45   0.805030  0.555950  0.140905           0      1
46   0.142046  0.640460  0.789578           2      1
47   0.128860  0.486328  0.911384           2      1
48   0.744583  0.595608  0.168113           0      1
49   0.147959  0.544381  0.867469           2      0
50   0.534162  0.733605  0.216952           1      0
51   0.814203  0.555044  0.131908           0      1
52   0.761586  0.572873  0.160650           0      1
53   0.496292  0.631103  0.356903           1      1
54   0.580297  0.779387  0.167452           1      1
55   0.273072  0.588439  0.675686           2      0
56   0.659361  0.540912  0.288775           0      1
57   0.430428  0.690918  0.344257           1      1
58   0.520257  0.663518  0.297561           1      0
59   0.284603  0.650462  0.550513           1      1
60   0.810096  0.551503  0.139852           0      1
61   0.474897  0.647570  0.354517           1      1
62   0.179450  0.693234  0.694433           2      0
63   0.204479  0.652891  0.677987           2      1
64   0.571181  0.626966  0.272477           1      1
65   0.040835  0.608336  0.955699           2      1
66   0.114667  0.570721  0.882482           2      0
67   0.415113  0.572961  0.513424           1      0
68   0.160816  0.628526  0.766817           2      1
69   0.066146  0.657114  0.907731           2      0
70   0.068888  0.547612  0.936192           2      0
71   0.265059  0.589938  0.679545           2      0
72   0.107562  0.459084  0.944243           2      0
73   0.669595  0.660927  0.175300           0      1
74   0.472083  0.719952  0.270909    

In [83]:
results_df[(results_df['prediction']==2) & (results_df['class']==0)]

0         1         2  prediction  class
0    0.102546  0.498812  0.924611           2      0
5    0.135259  0.535468  0.879398           2      0
18   0.230063  0.536431  0.790575           2      0
49   0.147959  0.544381  0.867469           2      0
55   0.273072  0.588439  0.675686           2      0
62   0.179450  0.693234  0.694433           2      0
66   0.114667  0.570721  0.882482           2      0
69   0.066146  0.657114  0.907731           2      0
70   0.068888  0.547612  0.936192           2      0
71   0.265059  0.589938  0.679545           2      0
72   0.107562  0.459084  0.944243           2      0
75   0.272955  0.553204  0.720056           2      0
76   0.078147  0.393876  0.973264           2      0
92   0.159377  0.681801  0.734598           2      0
96   0.082273  0.685997  0.850332           2      0
103  0.337791  0.595087  0.603597           2      0
118  0.320891  0.555659  0.668291           2      0
121  0.212812  0.654493  0.676633           2      0
130  0.130210  0.543792  0.883284           2      0
136  0.226920  0.562646  0.760864           2      0
137  0.113083  0.643764  0.842624           2      0
138  0.206490  0.608781  0.751217           2      0
149  0.203256  0.619344  0.731721           2      0
150  0.345731  0.568992  0.616104           2      0
152  0.206456  0.645359  0.669758           2      0
155  0.163436  0.611702  0.787116           2      0

In [84]:
results_df[(results_df['prediction']==0) & (results_df['class']==1)]

0         1         2  prediction  class
1    0.891340  0.508295  0.088668           0      1
3    0.735795  0.565221  0.186600           0      1
13   0.665153  0.655881  0.189436           0      1
16   0.723591  0.648639  0.144848           0      1
20   0.842871  0.533635  0.115462           0      1
23   0.696126  0.615073  0.190292           0      1
26   0.700875  0.592338  0.206982           0      1
29   0.731619  0.643961  0.138827           0      1
31   0.618307  0.586321  0.297972           0      1
35   0.710059  0.632455  0.158523           0      1
36   0.713489  0.683796  0.130950           0      1
42   0.825405  0.583174  0.106443           0      1
45   0.805030  0.555950  0.140905           0      1
48   0.744583  0.595608  0.168113           0      1
51   0.814203  0.555044  0.131908           0      1
52   0.761586  0.572873  0.160650           0      1
56   0.659361  0.540912  0.288775           0      1
60   0.810096  0.551503  0.139852           0      1
73   0.669595  0.660927  0.175300           0      1
78   0.732892  0.638720  0.150296           0      1
81   0.687235  0.560260  0.238623           0      1
82   0.588359  0.556661  0.328294           0      1
84   0.782282  0.551890  0.148423           0      1
85   0.680036  0.633635  0.183315           0      1
87   0.718859  0.584458  0.194224           0      1
94   0.635558  0.627535  0.232652           0      1
101  0.852395  0.576310  0.091145           0      1
102  0.699353  0.613960  0.195427           0      1
104  0.801451  0.686770  0.086480           0      1
106  0.699758  0.610066  0.193687           0      1
107  0.647781  0.586491  0.254583           0      1
108  0.839759  0.592288  0.100114           0      1
110  0.871065  0.520249  0.097757           0      1
115  0.778915  0.551585  0.162507           0      1
117  0.839351  0.502987  0.136099           0      1
120  0.801834  0.619879  0.109323           0      1
134  0.570617  0.530557  0.397178           0      1
147  0.786870  0.623125  0.114656           0      1
153  0.895988  0.468779  0.099288           0      1
157  0.750358  0.599545  0.154909           0      1
158  0.645766  0.620944  0.219951           0      1
159  0.737233  0.546542  0.209010           0      1

In [90]:
# TP + TN

TP_TN = results_df[((results_df['prediction']==2) & (results_df['class']==0)) | (results_df['prediction']==0) & (results_df['class']==1)]
print(len(TP_TN))
TP_TN

68


0         1         2  prediction  class
0    0.102546  0.498812  0.924611           2      0
1    0.891340  0.508295  0.088668           0      1
3    0.735795  0.565221  0.186600           0      1
5    0.135259  0.535468  0.879398           2      0
13   0.665153  0.655881  0.189436           0      1
16   0.723591  0.648639  0.144848           0      1
18   0.230063  0.536431  0.790575           2      0
20   0.842871  0.533635  0.115462           0      1
23   0.696126  0.615073  0.190292           0      1
26   0.700875  0.592338  0.206982           0      1
29   0.731619  0.643961  0.138827           0      1
31   0.618307  0.586321  0.297972           0      1
35   0.710059  0.632455  0.158523           0      1
36   0.713489  0.683796  0.130950           0      1
42   0.825405  0.583174  0.106443           0      1
45   0.805030  0.555950  0.140905           0      1
48   0.744583  0.595608  0.168113           0      1
49   0.147959  0.544381  0.867469           2      0
51   0.814203  0.555044  0.131908           0      1
52   0.761586  0.572873  0.160650           0      1
55   0.273072  0.588439  0.675686           2      0
56   0.659361  0.540912  0.288775           0      1
60   0.810096  0.551503  0.139852           0      1
62   0.179450  0.693234  0.694433           2      0
66   0.114667  0.570721  0.882482           2      0
69   0.066146  0.657114  0.907731           2      0
70   0.068888  0.547612  0.936192           2      0
71   0.265059  0.589938  0.679545           2      0
72   0.107562  0.459084  0.944243           2      0
73   0.669595  0.660927  0.175300           0      1
75   0.272955  0.553204  0.720056           2      0
76   0.078147  0.393876  0.973264           2      0
78   0.732892  0.638720  0.150296           0      1
81   0.687235  0.560260  0.238623           0      1
82   0.588359  0.556661  0.328294           0      1
84   0.782282  0.551890  0.148423           0      1
85   0.680036  0.633635  0.183315           0      1
87   0.718859  0.584458  0.194224           0      1
92   0.159377  0.681801  0.734598           2      0
94   0.635558  0.627535  0.232652           0      1
96   0.082273  0.685997  0.850332           2      0
101  0.852395  0.576310  0.091145           0      1
102  0.699353  0.613960  0.195427           0      1
103  0.337791  0.595087  0.603597           2      0
104  0.801451  0.686770  0.086480           0      1
106  0.699758  0.610066  0.193687           0      1
107  0.647781  0.586491  0.254583           0      1
108  0.839759  0.592288  0.100114           0      1
110  0.871065  0.520249  0.097757           0      1
115  0.778915  0.551585  0.162507           0      1
117  0.839351  0.502987  0.136099           0      1
118  0.320891  0.555659  0.668291           2      0
120  0.801834  0.619879  0.109323           0      1
121  0.212812  0.654493  0.676633           2      0
130  0.130210  0.543792  0.883284           2      0
134  0.570617  0.530557  0.397178           0      1
136  0.226920  0.562646  0.760864           2      0
137  0.113083  0.643764  0.842624           2      0
138  0.206490  0.608781  0.751217           2      0
147  0.786870  0.623125  0.114656           0      1
149  0.203256  0.619344  0.731721           2      0
150  0.345731  0.568992  0.616104           2      0
152  0.206456  0.645359  0.669758           2      0
153  0.895988  0.468779  0.099288           0      1
155  0.163436  0.611702  0.787116           2      0
157  0.750358  0.599545  0.154909           0      1
158  0.645766  0.620944  0.219951           0      1
159  0.737233  0.546542  0.209010           0      1

In [91]:
# CRITICAL MISSCLASSIFICTION (NEGATIVE AS POSITIVE OR POSITIE AS NEGATIVE)

FP_FN = results_df[((results_df['prediction']==2) & (results_df['class']==1)) | (results_df['prediction']==0) & (results_df['class']==0)]
print(len(FP_FN))
FP_FN

18


0         1         2  prediction  class
6    0.106394  0.473036  0.935816           2      1
7    0.119603  0.655646  0.797179           2      1
8    0.214895  0.516755  0.818575           2      1
21   0.062248  0.673162  0.898006           2      1
43   0.152557  0.420727  0.931454           2      1
46   0.142046  0.640460  0.789578           2      1
47   0.128860  0.486328  0.911384           2      1
63   0.204479  0.652891  0.677987           2      1
65   0.040835  0.608336  0.955699           2      1
68   0.160816  0.628526  0.766817           2      1
83   0.361003  0.572152  0.585043           2      1
97   0.666177  0.608398  0.216563           0      0
100  0.100880  0.262390  0.984814           2      1
116  0.085207  0.548574  0.923385           2      1
127  0.168575  0.570042  0.824918           2      1
133  0.291435  0.579843  0.667896           2      1
140  0.684173  0.588062  0.224697           0      0
160  0.300980  0.583172  0.654454           2      1

In [94]:
# NEGATIVE AS NEUTRAL

NN = results_df[(results_df['prediction']==1) & (results_df['class']==1)]
print(len(NN))
NN

53


0         1         2  prediction  class
2    0.506244  0.662116  0.307833           1      1
4    0.450417  0.779694  0.232185           1      1
11   0.630438  0.701516  0.162193           1      1
12   0.497595  0.738499  0.249726           1      1
14   0.454631  0.765575  0.248944           1      1
15   0.520845  0.658625  0.312413           1      1
17   0.386938  0.600018  0.534007           1      1
19   0.528681  0.631339  0.328937           1      1
24   0.420527  0.726503  0.320084           1      1
27   0.369616  0.647212  0.492697           1      1
28   0.494137  0.818126  0.167224           1      1
30   0.058196  0.852220  0.730293           1      1
32   0.218838  0.761525  0.533851           1      1
33   0.114406  0.743255  0.723973           1      1
34   0.510592  0.535730  0.452863           1      1
37   0.362472  0.798186  0.296027           1      1
39   0.490750  0.574472  0.431437           1      1
40   0.660620  0.708978  0.150856           1      1
53   0.496292  0.631103  0.356903           1      1
54   0.580297  0.779387  0.167452           1      1
57   0.430428  0.690918  0.344257           1      1
59   0.284603  0.650462  0.550513           1      1
61   0.474897  0.647570  0.354517           1      1
64   0.571181  0.626966  0.272477           1      1
74   0.472083  0.719952  0.270909           1      1
79   0.547794  0.656150  0.277932           1      1
80   0.214187  0.730482  0.559280           1      1
86   0.512177  0.618285  0.348587           1      1
88   0.346446  0.629348  0.530481           1      1
89   0.315162  0.651687  0.532742           1      1
90   0.302342  0.723899  0.477623           1      1
98   0.418879  0.625357  0.446357           1      1
105  0.419725  0.590305  0.509415           1      1
109  0.487879  0.583399  0.430873           1      1
111  0.612210  0.629653  0.249202           1      1
112  0.526932  0.717116  0.242140           1      1
113  0.077155  0.785617  0.738134           1      1
114  0.335141  0.670979  0.467193           1      1
119  0.186045  0.733934  0.612963           1      1
122  0.487735  0.728894  0.257405           1      1
123  0.514855  0.658456  0.310629           1      1
125  0.334843  0.637730  0.509570           1      1
128  0.293133  0.667073  0.543017           1      1
131  0.188431  0.720565  0.639338           1      1
132  0.387661  0.613744  0.506824           1      1
139  0.385944  0.786850  0.262818           1      1
141  0.417676  0.657783  0.399362           1      1
142  0.558818  0.601313  0.335876           1      1
143  0.186642  0.719079  0.633878           1      1
144  0.549895  0.647247  0.288493           1      1
145  0.444478  0.615166  0.446318           1      1
154  0.470541  0.567979  0.473959           1      1
156  0.247602  0.712632  0.533438           1      1

In [95]:
# POSITIVE AS NEUTRAL

PN = results_df[(results_df['prediction']==1) & (results_df['class']==0)]
print(len(PN))
PN

22


0         1         2  prediction  class
9    0.410257  0.632319  0.449694           1      0
10   0.394731  0.575934  0.563481           1      0
22   0.271917  0.651843  0.589307           1      0
25   0.420829  0.616327  0.451394           1      0
38   0.302612  0.645349  0.556045           1      0
41   0.617825  0.620355  0.262060           1      0
44   0.539422  0.608491  0.342120           1      0
50   0.534162  0.733605  0.216952           1      0
58   0.520257  0.663518  0.297561           1      0
67   0.415113  0.572961  0.513424           1      0
77   0.563345  0.640536  0.288438           1      0
91   0.481703  0.581242  0.450217           1      0
93   0.495118  0.578003  0.431095           1      0
95   0.494454  0.649303  0.337567           1      0
99   0.526748  0.584097  0.375792           1      0
124  0.579312  0.606392  0.317691           1      0
126  0.438328  0.697743  0.346783           1      0
129  0.282169  0.755284  0.444138           1      0
135  0.277681  0.691491  0.552361           1      0
146  0.281203  0.720784  0.483260           1      0
148  0.241451  0.724853  0.528179           1      0
151  0.356293  0.661653  0.475435           1      0